# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## The steps in this Cloud Build script set up the cluster
## to be used by the project. This script is separate
## from the regular infrastructure setup because it is intended
## to be a one-time setup, whereas the steps in cloudbuild.yaml
## are repeatable.

steps:
## CLUSTER CREATE ##

# Create a new cluster with the appropriate configuration for this application
- name: 'gcr.io/cloud-builders/gcloud'
  id: Create Cluster
  waitFor: ['-']
  args: [
    'container', 'clusters', 'create', 'gcpcluster',
    '--addons', 'HorizontalPodAutoscaling,HttpLoadBalancing,CloudRun',
    '--machine-type', 'e2-standard-4',
    '--num-nodes', '2',
    '--cluster-version', '${_CLUSTER_GKE_VERSION}',
    '--enable-stackdriver-kubernetes',
    '--workload-pool', '${PROJECT_ID}.svc.id.goog',
    '--enable-ip-alias',
    '--zone', 'us-east1-c'
  ]

## SERVICE ACCOUNT SETUP

# Create a service account for Config Connecter (if one does not already exist)
- name: 'gcr.io/cloud-builders/gcloud'
  id: Create Config Connector service account
  waitFor: ['-']
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
      gcloud iam service-accounts describe cnrm-system@${PROJECT_ID}.iam.gserviceaccount.com || gcloud iam service-accounts create cnrm-system

# Set up IAM role bindings for Config Connector
# See: https://cloud.google.com/iam/docs/understanding-roles#primitive_role_definitions
- name: 'gcr.io/cloud-builders/gcloud'
  id: Grant Owner permissions
  waitFor: ['Create Config Connector service account']
  args: [
      'projects','add-iam-policy-binding','${PROJECT_ID}',
      '--member=serviceAccount:cnrm-system@${PROJECT_ID}.iam.gserviceaccount.com',
      '--role=roles/owner'
  ]

# Set up the Workload Identity binding for Config Connector on the cluster
# See: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
- name: 'gcr.io/cloud-builders/gcloud'
  id: Create IAM policy binding
  waitFor: ['Create Config Connector service account', 'Create Cluster']
  args: [
      'iam','service-accounts','add-iam-policy-binding','cnrm-system@${PROJECT_ID}.iam.gserviceaccount.com',
      '--member=serviceAccount:${PROJECT_ID}.svc.id.goog[cnrm-system/cnrm-controller-manager]',
      '--role=roles/iam.workloadIdentityUser'
  ]

